[HEIDELPAYSUPPORT-110] Fix sales channel specific config for webhooks
unzerdev/shopware6 pull request #25
Opened 2021-06-15 10:58 UTC by ngoedde

2021-06-15 11:06 UTC, sixer1182 requested changes
Please update the changelog with a description of this fix.

2021-06-18 14:12 UTC, sixer1182 commented on composer.json
> +    "version": "2.0.22,
Here is something wrong

2021-06-18 14:13 UTC, sixer1182 requested changes
fix version in composer.json

2021-06-18 14:43 UTC, sixer1182 approved these changes

2021-06-18 14:45 UTC, JoeKre commented on composer.json
> +    "version": "2.0.22,
Fixed

2021-08-18 10:31 UTC, closed without merging