[RELEASE] v1.0.3.0
unzerdev/shopware6 pull request #6
Opened 2021-01-15 08:17 UTC by jinnoflife

2021-01-15 14:15 UTC, sixer1182 requested changes
3 places version please

2021-01-15 14:15 UTC, sixer1182 commented on src/Components/CancelService/CancelService.php
> +    protected function getOrderTransaction(string $orderTransactionId, Context $context): ?OrderTransactionEntity
Some describing comments would be nice.
Please add for next release.

2021-01-15 14:15 UTC, sixer1182 commented on src/Components/CancelService/CancelService.php
> +        $roundedAmountGross = (int) round($amountGross * (10 ** $decimalPrecision));
Comment in next release please.

2021-01-18 14:22 UTC, jinnoflife commented on composer.json
> +    "version": "1.0.3.0",
done

2021-01-19 09:50 UTC, sixer1182 approved these changes
LGTM

2021-01-19 09:50 UTC, merged